<template>
  <div>
  <div class="loadingio-spinner-eclipse-zysm5de8q2"><div class="ldio-0xim8uh9p42b">
    <div></div>
  </div></div>
  </div>

</template>
<style>
@keyframes ldio-0xim8uh9p42b {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.ldio-0xim8uh9p42b div {
  position: absolute;
  animation: ldio-0xim8uh9p42b 0.88s linear infinite;
  width: 117.78px;
  height: 117.78px;
  top: 16.61px;
  left: 16.61px;
  border-radius: 50%;
  box-shadow: 0 12.382px 0 0 #a1df13;
  transform-origin: 58.89px 65.081px;
}
.loadingio-spinner-eclipse-zysm5de8q2 {
  width: 151px;
  height: 151px;
  display: inline-block;
  overflow: hidden;
  background: #f1f2f3;
}
.ldio-0xim8uh9p42b {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-0xim8uh9p42b div { box-sizing: content-box; }
/* generated by https://loading.io/ */

</style>